name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Godot 4.2
        run: |
          echo "Downloading Godot 4.2..."
          wget https://github.com/godotengine/godot/releases/download/4.2/Godot_v4.2-stable_linux_headless.64.zip || {
              echo "Download failed. Attempting to download from latest release..."
              wget $(curl -s https://api.github.com/repos/godotengine/godot/releases/latest | grep "browser_download_url.*linux_headless" | cut -d '"' -f 4)
          }
          echo "Unzipping Godot..."
          unzip Godot_v4.2-stable_linux_headless.64.zip -d godot
          echo "Setting executable permissions..."
          chmod +x godot/Godot_v4.2-stable_linux_headless.64

      - name: Export Windows build
        run: |
          echo "Creating builds directory..."
          mkdir -p builds/windows
          echo "Exporting Windows build..."
          ./godot/Godot_v4.2-stable_linux_headless.64 --headless --export "Windows Desktop" builds/windows/game.exe || exit 1

      - name: Download Butler
        run: |
          echo "Downloading Butler..."
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/latest/archive/default
          echo "Unzipping Butler..."
          unzip butler.zip -d butler
          echo "Moving Butler to /usr/local/bin..."
          sudo mv butler/butler /usr/local/bin/butler
          echo "Setting Butler executable permissions..."
          chmod +x /usr/local/bin/butler

      - name: Deploy to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          echo "Deploying to Itch.io..."
          butler push builds/windows/ ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:${{ secrets.ITCH_CHANNEL }} || exit 1

      - name: Clean up previous artifacts
        run: |
          echo "Cleaning up previous builds..."
          rm -rf builds/windows/*
